#!/bin/sh /etc/rc.common
START=90

run_jmusupplicant()
{
    local enable
    local username
    local password
    local ifname
    local cmd
    config_get_bool enable $1 enable
    config_get username $1 username
    config_get password $1 password
    config_get ifname $1 ifname

    if [ $enable ] && [ $username ] && [ $password ] && [ $ifname ]; then
        local service
        local ipaddr
        local mask
        local midnight
        
        config_get service $1 service
        config_get ipaddr $1 ipaddr
        config_get mask $1 mask
        config_get_bool midnight $1 midnight

        if [ "$service" != "" ]; then cmd=$cmd" -s"$service;fi
        if [ "$ipaddr" != "" ]; then cmd=$cmd" --ip "$ipaddr;fi
        if [ "$mask" != "" ]; then cmd=$cmd" --mask "$mask;fi
        if [ $midnight ]; then cmd=$cmd" -n";fi

        jmusupplicant -u$username -p$password --interface_card $ifname $cmd
    fi
}

start()
{
    config_load jmusupplicant
    config_foreach run_jmusupplicant jmusupplicant
}

stop()
{
    killall jmusupplicant
}

restart()
{
    jmusupplicant -k
    sleep 1
    config_load jmusupplicant
    config_foreach run_jmusupplicant jmusupplicant
}
